# Generated by Django 5.2.4 on 2025-07-17 11:32

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.productdetailspage'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
