# Generated by Django 5.2.1 on 2025-07-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articleblogpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBlogPage',
            fields=[
                ('blogdetailspage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blogdetailspage')),
                ('youtube_video_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Video BLog Page',
                'verbose_name_plural': 'Videos Blog Page',
            },
            bases=('blog.blogdetailspage',),
        ),
        migrations.AlterModelOptions(
            name='articleblogpage',
            options={'verbose_name': 'Article BLog Page', 'verbose_name_plural': 'Articles Blog Page'},
        ),
    ]
