# Generated by Django 5.2.4 on 2025-07-17 11:23

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0001_initial'),
        ('wagtailimages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimageblock',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', wagtail.fields.RichTextField(blank=True)),
                ('banner_cta', models.CharField(blank=True, max_length=50)),
                ('content', wagtail.fields.StreamField([('cta', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'max_length': 60, 'null': True, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 260, 'null': True, 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Add a link if needed', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a link if needed', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Read More', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('button_page', 2), ('button_url', 3), ('button_text', 4)]], {})}, default=list)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('banner_page_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='carouselimageblock',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='home.homepage'),
        ),
    ]
