# Generated by Django 5.2.1 on 2025-06-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_content_homepage_banner_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_content',
            new_name='banner_cta',
        ),
    ]
