# Generated by Django 5.2.1 on 2025-06-03 20:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('cta', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'max_length': 60, 'null': True, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 260, 'null': True, 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Add a link if needed', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a link if needed', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Read More', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('button_page', 2), ('button_url', 3), ('button_text', 4)]], {})}, default=list),
        ),
    ]
