# Generated by Django 5.2.1 on 2025-07-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_carouselimageblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
    ]
