# Generated by Django 5.2.4 on 2025-07-17 11:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('text_and_title', 2), ('rich_text', 3), ('simple_text', 4), ('card_blocks', 12), ('cta_blocks', 17), ('button_blocks', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add a title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add some text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('stream.blocks.RichTextBlocks', (), {}), 4: ('stream.blocks.SimpleRichTextBlocks', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Add a link if needed', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 5), ('title', 6), ('text', 7), ('button_page', 8), ('button_url', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('card', 11)]], {}), 13: ('wagtail.blocks.RichTextBlock', (), {'max_length': 60, 'null': True, 'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'max_length': 260, 'null': True, 'required': True}), 15: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Add a link if needed', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Read More', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 13), ('text', 14), ('button_page', 15), ('button_url', 9), ('button_text', 16)]], {}), 18: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Add a page url, If added it would be primary button', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('page_url', 18), ('page_link', 9)]], {})}, default=list)),
                ('subtitle', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
