# Generated by Django 5.2.1 on 2025-06-03 13:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flex',
            name='content',
            field=wagtail.fields.StreamField([('text_and_title', 2), ('rich_text', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add a title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add some text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('stream.blocks.RichTextBlocks', (), {})}, default=list),
        ),
    ]
