# Generated by Django 5.2.1 on 2025-06-04 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media Links',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
