# Generated by Django 5.2.4 on 2025-07-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL')),
            ],
            options={
                'verbose_name': 'Social Media Links',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
