# Generated by Django 5.2.4 on 2025-07-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_settings', '0001_initial'),
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialinks',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
    ]
